name: invoicer
description: A Flutter desktop app for processing invoices and receipts with OpenAI
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  signals: ^6.0.2
  file_picker: ^10.1.9
  http: ^1.1.0
  shared_preferences: ^2.5.3
  syncfusion_flutter_pdf: ^31.2.3
  syncfusion_flutter_pdfviewer: ^31.2.3
  path: ^1.8.3
  intl: ^0.20.2
  timeago: ^3.6.1
  flutter_dotenv: ^6.0.0
  macos_ui: ^2.1.10
  macos_window_utils: ^1.8.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  csv: ^6.0.0
  excel: ^4.0.6
  fl_chart: ^1.1.1
  desktop_drop: ^0.7.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: false
  assets:
    - .env